name: 🐞 Error Report
description: File an error report
labels: ["Error"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for using OrcaSlicer and wanting to report an error.**
        
        Please note that this is only for reportings errors in the OrcaSlicer Wiki.
        For issues with OrcaSlicer itself, please use the main [OrcaSlicer GitHub repository](https://github.com/OrcaSlicer/OrcaSlicer/issues).
        
        Before filing, please check if the issue already exists (either open or closed) by using the search bar on the issues page. If it does, comment there. Even if it's closed, we can reopen it based on your comment.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this problem?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: error_page
    attributes:
      label: Wiki Page
      description: Which page or section of the wiki does this issue relate to?
      placeholder: e.g. quality_settings_line_width
    validations:
      required: true
  - type: textarea
    id: error_description
    attributes:
      label: Error description
      description: Please describe the error you encountered in detail.
      placeholder: e.g. "The instructions on this page did not work as expected because..."
    validations:
      required: true
  - type: textarea
    id: file_uploads
    attributes:
      label: Attachments to improve the page.
      description:  If you want to update some files (images, code snippets, etc.) to improve the wiki page, please attach them here.
      placeholder: |
        You can attach images, code snippets, or any other relevant files that would help improve the wiki page.
    validations:
      required: false
