name: 🚀 Entry Request / Enhancement
description: Suggest an improvement to make Orca Slicer even better!
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Entry request!

        If your idea is still at the formulation stage, or you're not sure it would
        be useful to many users, you can raise it as a discussion topic under [Ideas](https://github.com/OrcaSlicer/OrcaSlicer/discussions/categories/ideas)
        or you can raise it on the [Discord server](https://discord.gg/P4VE9UY9gJ).
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this feature request?
      description: |
        Please search to see if an issue already exists for a feature, or perhaps one similar.
        You can then comment and react so that we know know much interest there is in the feature request.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: enhancement_page
    attributes:
      label: Wiki Page
      description: Which page or section of the wiki does this issue relate to?
      placeholder: e.g. quality_settings_line_width
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature / Enhancement Description
      description: A clear and concise description of the enhancement or new page you'd like to see.
      placeholder: |
        e.g. "It would be great to have a page that explains how to set up custom supports because..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context, diagrams, illustations or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
